on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      #uses: https://github.com/yojota/yojota.cloud
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{secrets.FTP_HOST}}
        username: ${{secretes.FTP_USER}}
        password: ${{ secrets.FTP_PASSWORD }}
